
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: back
    ports:
      - "5000:5000"  
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: front
    ports:
      - "3000:3000"