# version: '3'
# networks:
#   app_net:
#     driver: bridge
# services:
#   frontend:
#     build:
#       context: ./musicrecommender/
#       dockerfile: ./DockerFile
#     restart: always
#     ports:
#       - "3000:3000"
#     networks:
#       - app_net
#   backend:
#     build:
#       context: ./server/
#       dockerfile: ./DockerFile
#     restart: always
#     ports:
#       - "127.0.0.1:5000:5000"
#     networks:
#       - app_net

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: back
    ports:
      - "5000:5000"  
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: front
    ports:
      - "3000:3000"